require:
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "config/environments/*"
    - "config/puma.rb"
    - "spec/spec_helper.rb"
    - "db/schema.rb"

### ルールのカスタマイズ

# 設定が厳しいので一旦全てfalseにする
# Metrics:
#   Enabled: false

# 文字列のfreeze
Style/FrozenStringLiteralComment:
  Enabled: false

# 文字列のダブルクォートチェック
Style/StringLiterals:
  Exclude:
  - "Rakefile"
  - "app/mailers/application_mailer.rb"
  - "config/boot.rb"

# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Exclude:
  - config/initializers/filter_parameter_logging.rb
