require:
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 感知したルール詳細を表示する
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "config/environments/*"
    - "config/puma.rb"
    - "spec/**/*"
    - "db/schema.rb"

### ルールのカスタマイズ
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/helpers/application_helper.rb'


# 文字列のダブルクォートチェック
Style/StringLiterals:
  Exclude:
  - 'Rakefile'
  - 'app/mailers/application_mailer.rb'
  - 'config/boot.rb'

# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Exclude:
  - config/initializers/filter_parameter_logging.rb

Style/SingleArgumentDig:
  Exclude:
  - config/initializers/cloudinary.rb
